name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: set up actions
      uses: actions/checkout@v3
      
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Generate AAR and APK files
      if: always()
      run: ./gradlew assembleDebug

    - name: Upload AAR files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: artifacts.zip
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          newquiz_uploads/build/outputs/aar
